spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:tcp://localhost:1521/mem:testdb
    username: sa
    password:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1500,expireAfterAccess=20s
    cache-names: